Add gluster mount

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -1,6 +1,8 @@
 #!/bin/bash
 set -e
 
+[ "$DEBUG" == "1" ] && set -x && set +e
+
 userConfPath="/etc/sftp-users.conf"
 userConfFinalPath="/var/run/sftp-users.conf"
 
@@ -123,5 +125,37 @@ if [ ! -f "$userConfFinalPath" ]; then
         unset f
     fi
 fi
+
+sleep 5
+export GLUSTER_HOSTS=`dig +short ${GLUSTER_HOST}`
+if [ -z "${GLUSTER_HOSTS}" ]; then
+   echo "*** ERROR: Could not determine which containers are part of Gluster service."
+   echo "*** Is Gluster service linked with the alias \"${GLUSTER_HOST}\"?"
+   echo "*** If not, please link gluster service as \"${GLUSTER_HOST}\""
+   echo "*** Exiting ..."
+   exit 1
+else
+   echo "GLUSTER_HOSTS set to ${GLUSTER_HOSTS}"
+fi
+
+ALIVE=0
+for glusterHost in ${GLUSTER_HOSTS}; do
+    echo "=> Checking if I can reach GlusterFS node ${glusterHost} ..."
+    if ping -c 10 ${glusterHost} >/dev/null 2>&1; then
+       echo "=> GlusterFS node ${glusterHost} is alive"
+       ALIVE=1
+       break
+    else
+       echo "*** Could not reach server ${glusterHost} ..."
+    fi
+done
+
+if [ "$ALIVE" == 0 ]; then
+   echo "ERROR: could not contact any GlusterFS node from this list: ${GLUSTER_HOSTS} - Exiting..."
+   exit 1
+fi
+
+echo "=> Mounting GlusterFS volume ${GLUSTER_VOL} from GlusterFS node ${glusterHost} ..."
+mount -t glusterfs ${glusterHost}:/${GLUSTER_VOL} ${GLUSTER_VOL_PATH}
 
 exec /usr/sbin/sshd -D
